name: certbot-dns-dnsmanager
base: core24
summary: dnsmanager.io DNS Authenticator plugin for Certbot
description: dnsmanager.io DNS Authenticator plugin for Certbot
grade: stable
confinement: strict
adopt-info: certbot-dns-dnsmanager
platforms:
  amd64:
  arm64:
    build-on: [amd64, arm64]
    build-for: [arm64]

parts:
  certbot-dns-dnsmanager:
    plugin: python
    source: .
    override-pull: |
        snapcraftctl pull
        snapcraftctl set-version `grep ^version $SNAPCRAFT_PART_SRC/setup.py | cut -f2 -d= | tr -d '"[:space:]'`
    build-environment:
      - SNAP_BUILD: "True"
  certbot-metadata:
    plugin: dump
    source: .
    stage: [setup.py, certbot-shared]
    override-pull: |
        snapcraftctl pull
        mkdir -p $SNAPCRAFT_PART_SRC/certbot-shared

slots:
  certbot:
    interface: content
    content: certbot-1
    read:
      - $SNAP/lib/python3.12/site-packages

plugs:
  certbot-metadata:
    interface: content
    content: metadata-1
    target: $SNAP/certbot-shared
